name: bhromon_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.12.4
  image_picker: ^1.1.2
  google_generative_ai: ^0.4.0
  http: ^1.2.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.7.0
  url_launcher: ^6.2.0
  permission_handler: ^11.4.0
  intl: ^0.19.0
  webview_flutter: ^4.4.2
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # assets:
  #  - assets/images/
  #  - assets/icons/

  #fonts:
  #  - family: Poppins
  #    fonts:
  #      - asset: assets/fonts/Poppins-Regular.ttf
  #      - asset: assets/fonts/Poppins-Bold.ttf
  #        weight: 700
  #      - asset: assets/fonts/Poppins-SemiBold.ttf
  #        weight: 600